name: Deploy Node.js app to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: change directory
        run: cd video-player-backend

      - name: Install dependencies
        run: npm ci

      - name: Write service account key to file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=serviceAccountKey.json" >> $GITHUB_ENV

      - name: Build & Deploy
        run: |
          npm run build   # optional
          node server.js   # or your server startup logic
